//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventApp_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int RecordId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AreaName { get; set; }
        public string Source { get; set; }
        public string ConditionName { get; set; }
        public string Description { get; set; }
        public Nullable<double> EventID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Reason { get; set; }
    }
}
